# Generated by Django 6.0.4 on 2026-04-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_booking_no_of_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='No_of_guests',
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_guests',
            field=models.IntegerField(default=1),
        ),
    ]
